// frontend/src/pages/EvaluationDetail.tsx
import React, { useEffect, useState } from 'react'
import { Card, Descriptions, Table, Tag, Tabs, Row, Col, Statistic, Progress } from 'antd'
import { useParams } from 'react-router-dom'
import dayjs from 'dayjs'
import ReactECharts from 'echarts-for-react'
import { getEvaluation, getEvaluationResults, getEvaluationSummary } from '@/api'
import type { Evaluation } from '@/types'

interface EvalResult {
  id: number
  evaluation_id: number
  qa_record_id: number
  metric_scores: Record<string, { score: number; error?: string }>
  created_at: string
}

interface Summary {
  overall_score: number
  metrics: Record<string, { mean: number; std: number; min: number; max: number }>
}

const EvaluationDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>()
  const [evaluation, setEvaluation] = useState<Evaluation | null>(null)
  const [results, setResults] = useState<EvalResult[]>([])
  const [summary, setSummary] = useState<Summary | null>(null)
  const [loading, setLoading] = useState(false)

  const fetchEvaluation = async () => {
    if (!id) return
    try {
      const data = await getEvaluation(Number(id))
      setEvaluation(data)
    } catch (e) {
      // 错误已在拦截器处理
    }
  }

  const fetchResults = async () => {
    if (!id) return
    setLoading(true)
    try {
      const data = await getEvaluationResults(Number(id))
      setResults(data)
    } finally {
      setLoading(false)
    }
  }

  const fetchSummary = async () => {
    if (!id) return
    try {
      const data = await getEvaluationSummary(Number(id))
      setSummary(data)
    } catch (e) {
      // 错误已在拦截器处理
    }
  }

  useEffect(() => {
    fetchEvaluation()
    fetchResults()
    fetchSummary()
  }, [id])

  const getStatusType = (status: string) => {
    const types: Record<string, 'success' | 'warning' | 'processing' | 'error' | 'default'> = {
      completed: 'success',
      running: 'processing',
      pending: 'default',
      failed: 'error',
    }
    return types[status] || 'default'
  }

  const metricsColumns = [
    { title: 'QA记录ID', dataIndex: 'qa_record_id', key: 'qa_record_id', width: 80 },
    ...((evaluation?.metrics || []).map(metric => ({
      title: metric,
      key: metric,
      render: (record: EvalResult) => {
        const score = record.metric_scores[metric]
        if (!score) return <Tag color="default">无</Tag>
        if (score.error) return <Tag color="error">错误</Tag>
        return <span>{score.score.toFixed(4)}</span>
      },
    }))),
    {
      title: '时间',
      dataIndex: 'created_at',
      key: 'created_at',
      width: 100,
      render: (date: string) => dayjs(date).format('MM-DD HH:mm'),
    },
  ]

  const barOption = {
    tooltip: { trigger: 'axis' },
    xAxis: {
      type: 'category',
      data: Object.keys(summary?.metrics || {}),
    },
    yAxis: { type: 'value', max: 1 },
    series: [
      {
        type: 'bar',
        data: Object.entries(summary?.metrics || {}).map(([_, v]) => ({
          value: v.mean,
          itemStyle: { color: '#1890ff' },
        })),
      },
    ],
  }

  const tabItems = [
    {
      key: 'summary',
      label: '评估摘要',
      children: (
        <>
          <Row gutter={16}>
            <Col span={8}>
              <Card>
                <Statistic
                  title="综合得分"
                  value={summary?.overall_score || 0}
                  precision={4}
                  suffix="/ 1.0"
                />
              </Card>
            </Col>
            <Col span={16}>
              <Card title="指标得分分布">
                <ReactECharts option={barOption} style={{ height: 200 }} />
              </Card>
            </Col>
          </Row>
          {summary && (
            <Card title="详细统计" style={{ marginTop: 16 }}>
              <Row gutter={16}>
                {Object.entries(summary.metrics).map(([metric, stats]) => (
                  <Col span={6} key={metric}>
                    <Card size="small" title={metric}>
                      <Statistic title="平均值" value={stats.mean} precision={4} />
                      <Statistic title="标准差" value={stats.std} precision={4} />
                      <Statistic title="最小值" value={stats.min} precision={4} />
                      <Statistic title="最大值" value={stats.max} precision={4} />
                    </Card>
                  </Col>
                ))}
              </Row>
            </Card>
          )}
        </>
      ),
    },
    {
      key: 'results',
      label: '详细结果',
      children: (
        <Table
          dataSource={results}
          columns={metricsColumns}
          rowKey="id"
          loading={loading}
          scroll={{ x: 'max-content' }}
        />
      ),
    },
  ]

  return (
    <Card title={evaluation?.name || '评估详情'}>
      <Descriptions bordered column={4} style={{ marginBottom: 16 }}>
        <Descriptions.Item label="状态">
          <Tag color={getStatusType(evaluation?.status || '')}>{evaluation?.status}</Tag>
        </Descriptions.Item>
        <Descriptions.Item label="数据集ID">{evaluation?.dataset_id}</Descriptions.Item>
        <Descriptions.Item label="RAG系统ID">{evaluation?.rag_system_id || '-'}</Descriptions.Item>
        <Descriptions.Item label="LLM模型ID">{evaluation?.llm_model_id}</Descriptions.Item>
        <Descriptions.Item label="评估指标">
          {evaluation?.metrics?.map(m => <Tag key={m}>{m}</Tag>)}
        </Descriptions.Item>
        <Descriptions.Item label="批次大小">{evaluation?.batch_size}</Descriptions.Item>
        <Descriptions.Item label="开始时间">
          {evaluation?.started_at ? dayjs(evaluation.started_at).format('YYYY-MM-DD HH:mm') : '-'}
        </Descriptions.Item>
        <Descriptions.Item label="完成时间">
          {evaluation?.completed_at ? dayjs(evaluation.completed_at).format('YYYY-MM-DD HH:mm') : '-'}
        </Descriptions.Item>
      </Descriptions>

      {evaluation?.status === 'completed' && <Tabs items={tabItems} />}
    </Card>
  )
}

export default EvaluationDetail

// frontend/src/views/EvaluationDetail.vue
<template>
  <div class="evaluation-detail">
    <el-card shadow="hover">
      <template #header>
        <div class="card-header">
          <span>{{ evaluation?.name || '评估详情' }}</span>
          <el-button @click="$router.push('/evaluations')">返回</el-button>
        </div>
      </template>

      <el-descriptions :column="4" border>
        <el-descriptions-item label="名称">{{ evaluation?.name }}</el-descriptions-item>
        <el-descriptions-item label="数据集">{{ getDatasetName(evaluation?.dataset_id) }}</el-descriptions-item>
        <el-descriptions-item label="状态">
          <el-tag :type="getStatusType(evaluation?.status)">
            {{ getStatusLabel(evaluation?.status) }}
          </el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="创建时间">{{ formatDate(evaluation?.created_at) }}</el-descriptions-item>
      </el-descriptions>
    </el-card>

    <!-- 指标汇总 -->
    <el-card shadow="hover" style="margin-top: 16px" v-if="summary">
      <template #header>
        <span>指标汇总</span>
      </template>

      <el-row :gutter="16">
        <el-col :span="24">
          <div ref="summaryChartRef" style="height: 300px"></div>
        </el-col>
      </el-row>

      <el-table :data="metricSummaryTable" stripe style="margin-top: 16px">
        <el-table-column prop="name" label="指标" />
        <el-table-column prop="mean" label="平均值" width="100">
          <template #default="{ row }">
            {{ row.mean.toFixed(4) }}
          </template>
        </el-table-column>
        <el-table-column prop="std" label="标准差" width="100">
          <template #default="{ row }">
            {{ row.std.toFixed(4) }}
          </template>
        </el-table-column>
        <el-table-column prop="min" label="最小值" width="100">
          <template #default="{ row }">
            {{ row.min.toFixed(4) }}
          </template>
        </el-table-column>
        <el-table-column prop="max" label="最大值" width="100">
          <template #default="{ row }">
            {{ row.max.toFixed(4) }}
          </template>
        </el-table-column>
        <el-table-column prop="median" label="中位数" width="100">
          <template #default="{ row }">
            {{ row.median.toFixed(4) }}
          </template>
        </el-table-column>
        <el-table-column prop="count" label="有效数量" width="100" />
      </el-table>
    </el-card>

    <!-- 评估结果 -->
    <el-card shadow="hover" style="margin-top: 16px">
      <template #header>
        <span>评估结果详情</span>
      </template>

      <el-table :data="results" v-loading="resultsLoading" stripe max-height="400">
        <el-table-column prop="qa_record_id" label="QA ID" width="80" />
        <el-table-column label="指标得分" min-width="400">
          <template #default="{ row }">
            <div v-for="(score, metric) in row.metric_scores" :key="metric" style="display: inline-block; margin-right: 8px">
              <el-tag :type="score.error ? 'danger' : 'success'" size="small">
                {{ metric }}: {{ score.error ? '失败' : score.score.toFixed(3) }}
              </el-tag>
            </div>
          </template>
        </el-table-column>
      </el-table>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useRoute } from 'vue-router'
import * as echarts from 'echarts'
import dayjs from 'dayjs'
import { getEvaluation, getEvaluationResults, getEvaluationSummary, getDatasets } from '@/api'
import type { Evaluation, Dataset } from '@/types'

const route = useRoute()
const evalId = Number(route.params.id)

const evaluation = ref<Evaluation | null>(null)
const datasets = ref<Dataset[]>([])
const results = ref<any[]>([])
const summary = ref<any>(null)
const resultsLoading = ref(false)
const summaryChartRef = ref<HTMLElement>()

const formatDate = (date?: string) => date ? dayjs(date).format('YYYY-MM-DD HH:mm') : '-'

const statusLabels: Record<string, string> = {
  pending: '待执行',
  running: '运行中',
  completed: '已完成',
  failed: '失败',
}

const getStatusLabel = (status?: string) => status ? statusLabels[status] || status : '-'

const getStatusType = (status?: string) => {
  if (!status) return 'info'
  const types: Record<string, string> = {
    completed: 'success',
    running: 'warning',
    pending: 'info',
    failed: 'danger',
  }
  return types[status] || 'info'
}

const getDatasetName = (id?: number) => {
  if (!id) return '-'
  const ds = datasets.value.find(d => d.id === id)
  return ds?.name || id
}

const metricSummaryTable = computed(() => {
  if (!summary?.value?.metrics_summary) return []
  return Object.entries(summary.value.metrics_summary).map(([name, data]) => ({
    name,
    ...data as any
  }))
})

const fetchEvaluation = async () => {
  evaluation.value = await getEvaluation(evalId)
}

const fetchResults = async () => {
  if (evaluation.value?.status !== 'completed') return
  resultsLoading.value = true
  try {
    results.value = await getEvaluationResults(evalId)
  } finally {
    resultsLoading.value = false
  }
}

const fetchSummary = async () => {
  if (evaluation.value?.status !== 'completed') return
  try {
    summary.value = await getEvaluationSummary(evalId)
    initChart()
  } catch (e) {
    // 无汇总数据
  }
}

const fetchDatasets = async () => {
  datasets.value = await getDatasets()
}

const initChart = () => {
  if (!summaryChartRef.value || !summary.value?.metrics_summary) return
  const chart = echarts.init(summaryChartRef.value)
  const data = Object.entries(summary.value.metrics_summary).map(([name, val]) => ({
    name,
    value: (val as any).mean
  }))
  chart.setOption({
    tooltip: { trigger: 'axis' },
    xAxis: { type: 'category', data: data.map(d => d.name) },
    yAxis: { type: 'value', min: 0, max: 1 },
    series: [{
      type: 'bar',
      data: data.map(d => d.value),
      itemStyle: { color: '#1890ff' }
    }]
  })
}

onMounted(async () => {
  await fetchDatasets()
  await fetchEvaluation()
  await fetchResults()
  await fetchSummary()
})
</script>

<style scoped>
.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>
